version: '3'

networks:
  backend_net:
    driver: bridge

services:
  backend:
    build: .
    image: it-dgc-verifier-service
    container_name: it-dgc-verifier-service
    ports:
      - 9080:9080        
    environment:
      - SERVER_PORT=9080
      - MONGO_DB_URI=mongodb://host.docker.internal:27017/DGC-dev
    volumes:
      - ./it-dgc-verifier-service/config:/it-dgc-verifier-service/config
    networks:
      - backend_net
  
