version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
  backend:
    build: .
    image: it-dgc-verifier-service
    container_name: it-dgc-verifier-service
    ports:
      - 9080:9080        
    environment:
      - SERVER_PORT=9080
      - MONGO_DB_URI=mongodb://mongodb:27017
    network_mode: host
  
  