version: '3'

networks:
  backend_net:
    driver: bridge

services:
  backend:
    build: .
    image: it-dgc-verifier-service
    container_name: it-dgc-verifier-service
    ports:
      - 9080:9080        
    environment:
      - SERVER_PORT=9080
      - MONGO_DB_URI=mongodb://mongo:27017/DGC-dev
    volumes:
      - ./config:/it-dgc-verifier-service/config
    networks:
      - backend_net

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - backend_net
  
